// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDJP4R3d1zsmABWpuZoKfUuiBP4_13bB4',
    appId: '1:892574752019:web:1da0036dc9444ef6690ee6',
    messagingSenderId: '892574752019',
    projectId: 'icheja-mobile',
    authDomain: 'icheja-mobile.firebaseapp.com',
    storageBucket: 'icheja-mobile.firebasestorage.app',
    measurementId: 'G-DXQ2XR2WB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_sEwoS_-Td0usSHxGr1vkejnZA8TJasg',
    appId: '1:892574752019:android:153f15e0e1bb7605690ee6',
    messagingSenderId: '892574752019',
    projectId: 'icheja-mobile',
    storageBucket: 'icheja-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCucnr2hrycMxW0lJL_TBChijgy0jOIJWI',
    appId: '1:892574752019:ios:9fea0ac9530298ab690ee6',
    messagingSenderId: '892574752019',
    projectId: 'icheja-mobile',
    storageBucket: 'icheja-mobile.firebasestorage.app',
    iosBundleId: 'com.example.ichejaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCucnr2hrycMxW0lJL_TBChijgy0jOIJWI',
    appId: '1:892574752019:ios:9fea0ac9530298ab690ee6',
    messagingSenderId: '892574752019',
    projectId: 'icheja-mobile',
    storageBucket: 'icheja-mobile.firebasestorage.app',
    iosBundleId: 'com.example.ichejaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDJP4R3d1zsmABWpuZoKfUuiBP4_13bB4',
    appId: '1:892574752019:web:06dbf3ca7f1c67f8690ee6',
    messagingSenderId: '892574752019',
    projectId: 'icheja-mobile',
    authDomain: 'icheja-mobile.firebaseapp.com',
    storageBucket: 'icheja-mobile.firebasestorage.app',
    measurementId: 'G-4J52DNG0CB',
  );
}
